### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by ddavidebor** [azuyalabs/Volta#19]
Hi, 

It’s a description of the functionality available somewhere? Or things like screenshots, installation instructions etc etc

**Comment by stelgenhof** [comment]
Hi @ddavidebor 
There are some [Wiki](https://github.com/azuyalabs/Volta/wiki) pages that may help you.

Unfortunately this project has not been updated a lot by me for more than a year. At the moment I don't have much time to work on this and contemplate if I should continue or not actually. I know there are some other similar projects available much more ahead that you may find more useable (e.g. Octofarm).

Cheers! Sacha
